refactor: re-design the branding page
sitcon-tw/branding pull request #6
Opened 2022-04-16 05:57 UTC by pan93412

## Online Demo

<https://pan93412.github.io/branding/>

## Screenshots

![desktop-large](https://user-images.githubusercontent.com/28441561/163663646-0d07ba17-09a3-4081-8deb-760e3a5e0c4c.png)

2022-04-16 05:57 UTC, pan93412 commented
r? @denny0223

2022-04-16 16:18 UTC, rschiang commented
感謝貢獻！

我覺得大方向（排版上）沒有什麼問題，接受 PR 之後仍然可以細修；然而這包 PR 有點太大了，有點難以 review。

能否請就以下方向做調整？

- [ ] 英文翻譯部分拆出（需要 SITCON 編輯組先行審稿，可能要在 HackMD 上進行協作）
- [ ] 資料夾結構調整部分拆出
- [ ] 標題部分避免引入新圖檔
- [ ] commit 部分先 `squash` 過再行提交

2022-04-16 16:26 UTC, rschiang commented
另先就設計內容部分羅列如下：

1. 建議 CSS 樣式上避免使用 `* { ... }` 套用樣式
  - 如欲除正規化網頁呈現，或許可以引入 `normalize.css` ?
2. jf粉圓的設計提案十分討喜、但並非 SITCON 正在使用的字體
  - SITCON logo 的官方字體是 Nimbus Sans，其他目前未規範 (@elct9620)
  - 可能要請 @Ti-wb 跟設計組討論一下是否要規範這部分，否則我就要收 PR 了 OuO)
3. （其他想到的部分補在這裡）

2022-04-17 02:10 UTC, pan93412 commented
> 感謝貢獻！
> 
> 我覺得大方向（排版上）沒有什麼問題，接受 PR 之後仍然可以細修；然而這包 PR 有點太大了，有點難以 review。
> 
> 在接受此 PR 前，能否請就以下方向做調整呢？
> 
> * [ ]  英文翻譯修改部分拆出（ [33cfa83](https://github.com/sitcon-tw/branding/commit/33cfa8341af1b80f66fffb233a0765c761ab641b) 已有 `en.html`）– @fanlan1210
> * [ ]  ~資料夾結構調整部分拆出~ （好像還好）
> * [ ]  標題部分避免引入新圖檔，盡量用標準 logo 發揮
> * [ ]  commit 部分先 `squash` 過再行提交

1. 我沒有修改英文翻譯耶，我主要是把 `en.html` 轉成同個設計，只是檔名改掉而已。
2. 因為這個 PR 主要就是重新構建專案，我傾向不拆開
3. 同意，我晚點處理
4. 考慮到 commit 太大且有細項，如果是要 squash 成一個提交，我傾向讓合併方自行在 GitHub squash & merge；但如果只是 squash 成幾個大點的話，我等等也會處理：
  <img width="458" alt="截圖 2022-04-17 上午10 08 16" src="https://user-images.githubusercontent.com/28441561/163697258-aef30233-b687-4ffb-9687-f11b37d0738e.png">

## TODO

- [ ] 把 SVG 標題轉成 [SITCON SVG] + 標題的形式
- [ ] squash 一部分提交

2022-04-17 02:14 UTC, pan93412 commented
> 另先就設計內容部分羅列討論如下：
> 
> 1. 建議 CSS 樣式上避免使用 `* { ... }` 套用樣式
>    
>    * 如欲除正規化網頁呈現，或許可以引入 [normalize.css](https://necolas.github.io/normalize.css/) ?
> 2. jf粉圓的設計提案十分討喜、但並非 SITCON 正在使用的字體
>    
>    * SITCON logo 的官方字體是 Nimbus Sans，印象中其他目前未規範 – @elct9620, @Ti-wb
> 
> 我覺得可以先就 1. 的部分修正，其他看小 t 跟設計組有無建議 OuO)

1. 我已經引入 normalize.css 了，只是我又重新定義了基礎的字體大小、字族及顏色：

```
* {
     font-family: 'Noto Sans TC', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
     font-size: 14px;
     color: rgba(0, 0, 0, 0.75);
 }
```

舉例來說，定義完基礎字體是 14px 之後，接下來我就可以宣告標題是它的 1.2 倍（1.2em）。所以我覺得這裡其實沒有什麼問題，而開發者也可以覆寫相關的樣式。

2. 這部分或許得交給小 t 決定。SITCON 2022 有使用 Noto Serif TC 的例子，但套用在這裡其實並不是很合適。

2022-04-17 02:36 UTC, pan93412 commented
r? @rschiang

2022-04-17 03:13 UTC, rschiang requested changes
已 review。一開始是看到新下的英文標題所以以為有修改翻譯。XD

我另外 assign 設計組的人幫忙看哦。

2022-04-17 03:13 UTC, rschiang commented on english.html
> +            <div class="right">Terms of Brand Use</div>
~~Terms of Brand Use~~ → **Brand Guidelines**

2022-04-17 03:54 UTC, rschiang approved these changes
我覺得 OK，設計組沒意見的話，大概晚上就會 merge 囉。owo)

2022-04-17 14:36 UTC, Ti-wb commented
感謝貢獻！
整體方向我也覺得是沒問題的，主要我會有疑慮的部分就在於中文字型的使用，雖說 jf 粉圓的效果不錯
但這裡我仍傾向使用 SITCON 歷年網站與各式印刷物常用的 Noto Sans CJK TC

2022-04-17 14:38 UTC, Ti-wb approved these changes

2022-04-17 14:45 UTC, rschiang commented
> 舉例來說，定義完基礎字體是 14px 之後，接下來我就可以宣告標題是它的 1.2 倍（1.2em），所以我覺得這裡其實沒有什麼問題。

比較標準的定義法應該是對根元素 (`:root`, `html`) 定義，然後用 `em` 或是 `rem` 套用變化吧。owo)
設計組這邊確認過，那我就先收啦！感謝您的貢獻與協作 (・ω・)ノ

2022-04-17 14:45 UTC, YuRen-tw commented on index.html
> +            </section>
這樣的 `<section>` 用法是合理的嗎？
如果只是想要單純的容器，用 `<div>` 是不是會更好？

2022-04-17 14:47 UTC, merged

2022-04-17 14:49 UTC, rschiang commented on index.html
> +            </section>
我也覺得可以調整一下XD
皮皮可以直接開個 PR! 我應該也會讓 @tonyhhyip 針對他之前自己寫的英文開 PR!

2022-04-17 14:50 UTC, pan93412 commented on index.html
> +            </section>
對耶，應該是重構語意化標籤時搞錯了。你可以幫我發個 PR 修正嗎？謝謝～

2022-04-17 14:53 UTC, pan93412 commented
> > 舉例來說，定義完基礎字體是 14px 之後，接下來我就可以宣告標題是它的 1.2 倍（1.2em），所以我覺得這裡其實沒有什麼問題。
> 
> 比較標準的定義法應該是對根元素 (`:root`, `html`) 定義，然後用 `em` 或是 `rem` 套用變化吧。owo) 設計組這邊確認過，那我就先收啦！感謝您的貢獻與協作 (・ω・)ノ

同意，想 cc 給 @YuRen-tw 讓他跟著 section 的問題一併修正。感謝提供更好的建議～